name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make build_test_image
      - run: |
          npm install
      - run: |
          npm run migrations
          npm run test
