name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.15
      - run: |
          npm install
      - env:
          DB_PROD_HOST: localhost
          DB_PROD_PORT: 5432
          DB_PROD_USER: postgres
          DB_PROD_PASS: postgres
          GOOGLE_CLIENT_ID: wrong_id
        run: |
          npm run test
