name: Deploy and Migrations

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Copy SSH build to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrest.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "., !node_modules"
          target: "~/app/vipo-api"
