name: "run migration in test"
on:
  pull_request:
  push:
    branches:
      - master
#So this CI is to we run your migrations
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - env:
          DB_PROD_HOST: localhost
          DB_PROD_PORT: 5433
          DB_PROD_USER: postgres
          DB_PROD_PASS: postgres
          MIGRATAION: false
          GOOGLE_CLIENT_ID: wrong_id
        run: |
          npm run migrations-test
